import { TopicContent } from './topic.model';

export const TOPIC_CONTENT: Record<string, TopicContent> = {
  'creating-a-new-angular-project': {
    title: 'Creating a New Angular Project',
    whatIsIt:
      'An Angular project is a workspace generated by the Angular CLI. The CLI creates the folder structure, TypeScript configuration, build pipeline and a first component so you can start writing features immediately.',
    whyUseIt:
      'Setting up a bundler, TypeScript, testing and a dev server by hand takes hours and is easy to get wrong. The CLI gives you a production-ready setup in one command, plus generators for components, services and pipes.',
    whenToUseIt:
      'Any time you start a new Angular app or add a new library to an existing workspace. Use "ng generate" for every new file instead of copying folders by hand.',
    realWorldScenario:
      'Your team is starting an internal admin portal. You run "ng new admin-portal --style=scss --ssr=false", commit the scaffold on day one, and everyone clones a working project with the same build, lint and test commands. New pages are added with "ng generate component" so the whole codebase stays consistent.',
    codeExamples: [
      {
        caption: 'Create a workspace and start the dev server',
        code: `npm install -g @angular/cli

ng new angular-mastery --style=scss --routing
cd angular-mastery
npm start          # serves on http://localhost:4200
npm run build      # production build into dist/`
      },
      {
        caption: 'The files that matter most',
        code: `src/
  main.ts            # bootstraps the root component
  index.html         # single page that hosts <app-root>
  styles.scss        # global styles
  app/
    app.ts           # root standalone component
    app.html         # root template
    app.config.ts    # providers: router, http, ...
    app.routes.ts    # URL -> component map`
      },
      {
        caption: 'Generating new pieces',
        code: `ng generate component dashboard   # component + template + styles + spec
ng generate service auth          # injectable service
ng generate pipe truncate         # standalone pipe`
      }
    ]
  },

  '01-components': {
    title: 'Components',
    whatIsIt:
      'A component is a class decorated with @Component that owns a piece of the screen. It has a template (HTML), styles, and a class where you keep the data and behaviour for that piece of UI. In Angular 20 components are standalone by default: they declare their own imports and need no NgModule.',
    whyUseIt:
      'Components split a big screen into small named pieces you can understand, reuse and test on their own. Styles are scoped to the component, so a change in one card cannot accidentally restyle the whole app.',
    whenToUseIt:
      'Whenever a part of the UI has its own data or behaviour, or repeats more than once: a card, a navbar, a modal, a whole page. If a template grows past a screenful, that is a hint to split it into child components.',
    realWorldScenario:
      'On an e-commerce product page you build ProductGalleryComponent, ProductInfoComponent and AddToCartComponent. The page component only lays them out. When marketing asks for a new "compare" page, you reuse the gallery component untouched.',
    codeExamples: [
      {
        caption: 'A standalone component with an input',
        code: `import { Component, input, output } from '@angular/core';

@Component({
  selector: 'app-product-card',
  templateUrl: './product-card.component.html',
  styleUrl: './product-card.component.scss'
})
export class ProductCardComponent {
  // signal inputs: parent passes [product]="p"
  product = input.required<Product>();
  // parent listens with (addToCart)="onAdd($event)"
  addToCart = output<Product>();

  add(): void {
    this.addToCart.emit(this.product());
  }
}`
      },
      {
        caption: 'Its template and how a parent uses it',
        code: `<!-- product-card.component.html -->
<article class="card">
  <h3>{{ product().name }}</h3>
  <p>{{ product().price | currency }}</p>
  <button (click)="add()">Add to cart</button>
</article>

<!-- parent template -->
<app-product-card [product]="selected()" (addToCart)="cart.add($event)" />`
      }
    ]
  },

  '02-data-binding': {
    title: 'Data Binding',
    whatIsIt:
      'Data binding is the connection between your component class and its template. Angular supports interpolation {{ value }}, property binding [prop]="value", event binding (click)="handler()", and two-way binding [(ngModel)]="value" or [(value)]="signal".',
    whyUseIt:
      'You describe what the UI should show and Angular keeps the DOM in sync. No manual querySelector, no innerHTML updates, and no risk of the screen drifting out of step with your data.',
    whenToUseIt:
      'Interpolation for text, property binding for element or component inputs, event binding for user actions, two-way binding for form controls and editable values.',
    realWorldScenario:
      'In a support-ticket app the agent edits a reply box. The textarea is two-way bound to a signal, a character counter reads the same signal through interpolation, and the Send button is disabled with a property binding until the text is long enough.',
    codeExamples: [
      {
        caption: 'All four binding styles',
        code: `<!-- 1. interpolation -->
<p>Hello {{ userName() }}, you have {{ unread() }} messages</p>

<!-- 2. property binding -->
<img [src]="avatarUrl()" [alt]="userName()">
<button [disabled]="reply().length < 10">Send</button>

<!-- 3. event binding -->
<button (click)="send()">Send</button>
<input (keyup.enter)="send()">

<!-- 4. two-way binding on a signal (model input) -->
<textarea [(ngModel)]="reply"></textarea>`
      },
      {
        caption: 'Two-way binding your own component with model()',
        code: `import { Component, model } from '@angular/core';

@Component({
  selector: 'app-rating',
  template: \`
    @for (star of [1,2,3,4,5]; track star) {
      <button (click)="value.set(star)">{{ star <= value() ? '*' : '-' }}</button>
    }
  \`
})
export class RatingComponent {
  value = model(0);   // parent: <app-rating [(value)]="score" />
}`
      }
    ]
  },

  '03-directives': {
    title: 'Directives',
    whatIsIt:
      'A directive adds behaviour to an existing element. Attribute directives such as ngClass, ngStyle and ngModel change appearance or behaviour; structural directives change the DOM layout. Modern Angular replaces most structural directives with the built-in control flow blocks.',
    whyUseIt:
      'Directives let you reuse small pieces of DOM behaviour across many templates without wrapping everything in extra components or duplicating logic.',
    whenToUseIt:
      'Use ngClass / ngStyle for dynamic styling, ngModel for simple form inputs, and RouterLink for navigation. Write your own directive when the same behaviour (tooltip, autofocus, permission check) is needed in many places.',
    realWorldScenario:
      'A monitoring dashboard colours each server row by status. Instead of building a component per status, one ngClass binding maps status to a CSS class, and a small custom directive highlights rows that changed in the last minute.',
    codeExamples: [
      {
        caption: 'Built-in attribute directives',
        code: `<tr [ngClass]="{ ok: server.up, down: !server.up }"
    [ngStyle]="{ 'border-left-color': server.color }">
  <td>{{ server.name }}</td>
</tr>

<input [(ngModel)]="query" placeholder="Filter servers">
<a [routerLink]="['/server', server.id]">Details</a>`
      },
      {
        caption: 'Importing what a standalone template needs',
        code: `import { NgClass } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-server-list',
  imports: [NgClass, FormsModule, RouterLink],
  templateUrl: './server-list.component.html'
})
export class ServerListComponent {}`
      }
    ]
  },

  '04-control-flow': {
    title: 'Control Flow',
    whatIsIt:
      'Built-in template blocks that decide what gets rendered: @if / @else if / @else, @for with a required track expression and an optional @empty block, and @switch / @case / @default. They are part of the template language, so no imports are needed.',
    whyUseIt:
      'The blocks read like normal code, are faster than the old *ngIf and *ngFor directives, and the compiler checks them. The mandatory track expression keeps list updates efficient by reusing DOM nodes.',
    whenToUseIt:
      'Every time the UI depends on data: showing a spinner while loading, rendering a list, or picking one of several states. Use @switch instead of a long @else if chain.',
    realWorldScenario:
      'An orders page loads asynchronously. @if shows a skeleton while loading, an error panel on failure, and the table on success. Inside the table @for renders each order with track order.id, and @empty shows "No orders yet" for new customers.',
    codeExamples: [
      {
        caption: '@if / @for / @empty',
        code: `@if (loading()) {
  <app-skeleton />
} @else if (error()) {
  <p class="error">{{ error() }}</p>
} @else {
  <ul>
    @for (order of orders(); track order.id) {
      <li>{{ order.reference }} - {{ order.total | currency }}</li>
    } @empty {
      <li>No orders yet</li>
    }
  </ul>
}`
      },
      {
        caption: '@switch and @let',
        code: `@let status = order().status;

@switch (status) {
  @case ('paid')    { <span class="badge green">Paid</span> }
  @case ('pending') { <span class="badge amber">Pending</span> }
  @default          { <span class="badge grey">{{ status }}</span> }
}`
      }
    ]
  },

  '05-signals': {
    title: 'Signals',
    whatIsIt:
      'A signal is a value wrapper that knows who reads it. You read it by calling it, update it with set() or update(), derive new values with computed(), and react to changes with effect(). Angular re-renders only the parts of the UI that actually read the changed signal.',
    whyUseIt:
      'Signals make state explicit and change detection precise, which means fewer bugs and better performance than checking whole component trees. Derived state stays in sync automatically, so you never forget to recalculate a total.',
    whenToUseIt:
      'For nearly all component state in Angular 20: form values, toggles, loaded data, and anything derived from them. Prefer computed() over methods called from the template, and keep effect() for side effects like logging or localStorage.',
    realWorldScenario:
      'A shopping cart service keeps items in a signal. The header badge reads a computed count, the cart page reads a computed subtotal with tax, and an effect saves the cart to localStorage. Adding an item updates all three with one set() call.',
    codeExamples: [
      {
        caption: 'signal, computed and effect',
        code: `import { Injectable, computed, effect, signal } from '@angular/core';

@Injectable({ providedIn: 'root' })
export class CartService {
  private readonly items = signal<CartItem[]>([]);

  readonly count    = computed(() => this.items().reduce((n, i) => n + i.qty, 0));
  readonly subtotal = computed(() => this.items().reduce((s, i) => s + i.qty * i.price, 0));

  constructor() {
    effect(() => localStorage.setItem('cart', JSON.stringify(this.items())));
  }

  add(item: CartItem): void {
    this.items.update((current) => [...current, item]);
  }

  clear(): void {
    this.items.set([]);
  }
}`
      },
      {
        caption: 'linkedSignal and resource for async data',
        code: `import { resource, signal } from '@angular/core';

const userId = signal(1);

const user = resource({
  params: () => ({ id: userId() }),
  loader: ({ params }) => fetch('/api/users/' + params.id).then((r) => r.json())
});

// template: @if (user.isLoading()) { ... } @else { {{ user.value()?.name }} }`
      }
    ]
  },

  '06-routing': {
    title: 'Routing',
    whatIsIt:
      'The Angular Router maps URL paths to components. You declare routes in an array, register them with provideRouter(routes), and render the matched component inside <router-outlet>. Navigation happens with routerLink in templates or Router.navigate() in code.',
    whyUseIt:
      'Users expect back/forward buttons, bookmarkable URLs and shareable links. The router gives you those in a single-page app, plus lazy loading, guards and route data.',
    whenToUseIt:
      'As soon as your app has more than one screen. Use route parameters for entity pages (/order/42) and query parameters for filters and pagination.',
    realWorldScenario:
      'A helpdesk app has /tickets, /tickets/:id and /settings. Support agents paste ticket URLs into chat and the app opens the exact ticket. A wildcard route sends unknown URLs to a friendly not-found page.',
    codeExamples: [
      {
        caption: 'Route configuration',
        code: `import { Routes } from '@angular/router';
import { TicketListComponent } from './tickets/ticket-list.component';

export const routes: Routes = [
  { path: '', component: TicketListComponent, title: 'Tickets' },
  {
    path: 'tickets/:id',
    loadComponent: () => import('./tickets/ticket-detail.component')
      .then((m) => m.TicketDetailComponent)
  },
  { path: '**', redirectTo: '' }
];`
      },
      {
        caption: 'Reading params and navigating',
        code: `import { Component, inject, input } from '@angular/core';
import { Router } from '@angular/router';

@Component({ selector: 'app-ticket-detail', templateUrl: './ticket-detail.component.html' })
export class TicketDetailComponent {
  private readonly router = inject(Router);

  // with withComponentInputBinding() the :id param arrives as an input
  id = input.required<string>();

  close(): void {
    this.router.navigate(['/'], { queryParams: { closed: this.id() } });
  }
}`
      }
    ]
  },

  '07-services': {
    title: 'Services',
    whatIsIt:
      'A service is a plain class marked with @Injectable that holds logic or state shared by several components: API calls, caching, business rules, or app-wide state. With providedIn: "root" a single instance is created and shared.',
    whyUseIt:
      'Components should be about the screen, not about how data is fetched or calculated. Moving that work into services removes duplication, makes the logic testable without any DOM, and lets unrelated components share the same state.',
    whenToUseIt:
      'Whenever two components need the same data or the same rule, or when a component file starts mixing UI with fetching, parsing and validation.',
    realWorldScenario:
      'A booking app has a RoomService that loads rooms, caches them for five minutes and exposes a signal. The search page, the calendar view and the admin table all inject the same service, so a booking made in one view is instantly visible in the others.',
    codeExamples: [
      {
        caption: 'A stateful service',
        code: `import { Injectable, computed, inject, signal } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Injectable({ providedIn: 'root' })
export class RoomService {
  private readonly http = inject(HttpClient);
  private readonly rooms = signal<Room[]>([]);

  readonly available = computed(() => this.rooms().filter((r) => !r.booked));

  load(): void {
    this.http.get<Room[]>('/api/rooms').subscribe((rooms) => this.rooms.set(rooms));
  }
}`
      },
      {
        caption: 'Using it in a component',
        code: `@Component({ selector: 'app-room-search', templateUrl: './room-search.component.html' })
export class RoomSearchComponent {
  private readonly service = inject(RoomService);
  readonly rooms = this.service.available;

  constructor() {
    this.service.load();
  }
}`
      }
    ]
  },

  '08-dependency-injection': {
    title: 'Dependency Injection',
    whatIsIt:
      'Dependency injection (DI) is Angular creating and supplying the objects your class needs. You declare what you want with inject(Token) (or a constructor parameter) and Angular looks it up in the injector tree, creating it once per provider scope.',
    whyUseIt:
      'Your classes stop caring how their collaborators are built, so you can swap a real API service for a fake in tests, provide different configuration per environment, and avoid global singletons you cannot control.',
    whenToUseIt:
      'For every service, HttpClient, Router, or configuration value a class needs. Use InjectionToken for plain values, and route- or component-level providers when an instance should not be global.',
    realWorldScenario:
      'A white-label product ships to several clients. An APP_CONFIG injection token supplies the API base URL and theme per deployment; components and services inject the token instead of reading globals, so tests provide a stub config in one line.',
    codeExamples: [
      {
        caption: 'inject() and an InjectionToken',
        code: `import { InjectionToken, inject } from '@angular/core';

export interface AppConfig { apiUrl: string; theme: 'light' | 'dark'; }
export const APP_CONFIG = new InjectionToken<AppConfig>('APP_CONFIG');

// app.config.ts
providers: [
  { provide: APP_CONFIG, useValue: { apiUrl: '/api', theme: 'dark' } }
]

// anywhere
export class ReportService {
  private readonly config = inject(APP_CONFIG);
  private readonly http = inject(HttpClient);

  list() {
    return this.http.get<Report[]>(this.config.apiUrl + '/reports');
  }
}`
      },
      {
        caption: 'Swapping an implementation in a test',
        code: `TestBed.configureTestingModule({
  providers: [
    { provide: APP_CONFIG, useValue: { apiUrl: 'http://test', theme: 'light' } },
    { provide: RoomService, useClass: FakeRoomService }
  ]
});`
      }
    ]
  },

  '09-http-client': {
    title: 'HTTP Client',
    whatIsIt:
      'HttpClient is Angular service for calling HTTP APIs. You enable it once with provideHttpClient() and then use get, post, put, patch and delete, which return observables of typed responses.',
    whyUseIt:
      'It handles JSON parsing, typed responses, request options, cancellation and error objects, and it plugs into interceptors and testing utilities that fetch alone does not provide.',
    whenToUseIt:
      'For all communication with your backend or third-party REST APIs. Use httpResource() when you just need to load data into a signal for display, and HttpClient directly for commands like saving a form.',
    realWorldScenario:
      'An invoicing app loads a paginated invoice list with query params, posts a new invoice from a form, and downloads a PDF with responseType: "blob". All calls go through provideHttpClient so an auth interceptor attaches the token.',
    codeExamples: [
      {
        caption: 'Enable and call an API',
        code: `// app.config.ts
import { provideHttpClient, withFetch } from '@angular/common/http';

export const appConfig: ApplicationConfig = {
  providers: [provideHttpClient(withFetch())]
};

// invoice.service.ts
@Injectable({ providedIn: 'root' })
export class InvoiceService {
  private readonly http = inject(HttpClient);

  list(page: number) {
    return this.http.get<Page<Invoice>>('/api/invoices', {
      params: { page, size: 20 }
    });
  }

  create(invoice: NewInvoice) {
    return this.http.post<Invoice>('/api/invoices', invoice);
  }
}`
      },
      {
        caption: 'Signal-based loading with httpResource',
        code: `import { httpResource } from '@angular/common/http';

export class InvoiceListComponent {
  readonly page = signal(1);
  readonly invoices = httpResource<Page<Invoice>>(() => ({
    url: '/api/invoices',
    params: { page: this.page() }
  }));
  // template: @if (invoices.isLoading()) { ... } @else { @for (i of invoices.value()?.items ?? []; ...
}`
      }
    ]
  },

  '10-rxjs': {
    title: 'RxJS',
    whatIsIt:
      'RxJS is a library for working with streams of values over time. An Observable emits values, and operators like map, filter, debounceTime and switchMap transform or combine those streams before you subscribe.',
    whyUseIt:
      'Some problems are naturally streams: typeahead search, websockets, polling, drag events, retries. RxJS gives you cancellation and composition that promises cannot express, and Angular HTTP and router APIs already return observables.',
    whenToUseIt:
      'For event streams and coordinated async work. For simple state prefer signals, and convert between the two with toSignal() and toObservable() from @angular/core/rxjs-interop.',
    realWorldScenario:
      'A product search box fires a request per keystroke. With debounceTime(300), distinctUntilChanged() and switchMap the app sends one request after the user stops typing and cancels stale responses, so results never arrive out of order.',
    codeExamples: [
      {
        caption: 'Typeahead search',
        code: `import { toSignal } from '@angular/core/rxjs-interop';
import { debounceTime, distinctUntilChanged, switchMap } from 'rxjs';

export class SearchComponent {
  private readonly http = inject(HttpClient);
  readonly term = signal('');

  private readonly results$ = toObservable(this.term).pipe(
    debounceTime(300),
    distinctUntilChanged(),
    switchMap((q) => this.http.get<Product[]>('/api/search', { params: { q } }))
  );

  readonly results = toSignal(this.results$, { initialValue: [] as Product[] });
}`
      },
      {
        caption: 'Error handling and cleanup',
        code: `import { catchError, of, takeUntilDestroyed } from 'rxjs';

this.http.get<Order[]>('/api/orders')
  .pipe(
    catchError((err) => { console.error(err); return of([]); }),
    takeUntilDestroyed(this.destroyRef)
  )
  .subscribe((orders) => this.orders.set(orders));`
      }
    ]
  },

  '11-forms': {
    title: 'Forms',
    whatIsIt:
      'Angular offers two form styles. Template-driven forms use ngModel directly in the template for simple cases. Reactive forms build a FormGroup of FormControls in the class, giving you typed values, validators and full control in code.',
    whyUseIt:
      'Forms need validation, error messages, dirty/touched state and submit handling. Angular forms provide all of it consistently instead of hand-rolled state per input.',
    whenToUseIt:
      'Template-driven for a login box or a filter with two fields. Reactive for anything larger: dynamic fields, cross-field validation, wizards, or forms whose values must be tested.',
    realWorldScenario:
      'An onboarding wizard collects company details, addresses (a FormArray you can add rows to) and a password with a custom "must match confirmation" validator. The Next button stays disabled while the current step is invalid, and errors appear only after a field is touched.',
    codeExamples: [
      {
        caption: 'Typed reactive form with validation',
        code: `import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';

@Component({
  selector: 'app-signup',
  imports: [ReactiveFormsModule],
  templateUrl: './signup.component.html'
})
export class SignupComponent {
  private readonly fb = inject(FormBuilder);

  readonly form = this.fb.nonNullable.group({
    email: ['', [Validators.required, Validators.email]],
    password: ['', [Validators.required, Validators.minLength(8)]],
    addresses: this.fb.array<FormGroup>([])
  });

  submit(): void {
    if (this.form.invalid) { this.form.markAllAsTouched(); return; }
    console.log(this.form.getRawValue());   // fully typed
  }
}`
      },
      {
        caption: 'Template with error messages',
        code: `<form [formGroup]="form" (ngSubmit)="submit()">
  <input formControlName="email" placeholder="Email">
  @if (form.controls.email.touched && form.controls.email.invalid) {
    <small class="error">Enter a valid email</small>
  }

  <input formControlName="password" type="password">
  <button [disabled]="form.invalid">Create account</button>
</form>`
      }
    ]
  },

  '12-custom-directives': {
    title: 'Custom Directives',
    whatIsIt:
      'A custom directive is a standalone class with @Directive and a selector, usually an attribute. It can read inputs, listen to host events with host bindings, and manipulate its element through ElementRef or Renderer2.',
    whyUseIt:
      'It packages DOM behaviour without adding a wrapper element or duplicating listeners in every component. One directive can be dropped onto any element in any template.',
    whenToUseIt:
      'For cross-cutting UI behaviour: autofocus, click-outside, tooltips, infinite-scroll triggers, permission-based hiding, input masks.',
    realWorldScenario:
      'An admin app hides actions the current user cannot perform. A hasRole directive checks the auth service and removes the element from the DOM, so every "Delete" button just adds hasRole="admin" instead of repeating @if checks.',
    codeExamples: [
      {
        caption: 'A structural permission directive',
        code: `import { Directive, TemplateRef, ViewContainerRef, effect, inject, input } from '@angular/core';

@Directive({ selector: '[hasRole]' })
export class HasRoleDirective {
  private readonly tpl = inject(TemplateRef<unknown>);
  private readonly view = inject(ViewContainerRef);
  private readonly auth = inject(AuthService);

  hasRole = input.required<string>();

  constructor() {
    effect(() => {
      this.view.clear();
      if (this.auth.roles().includes(this.hasRole())) {
        this.view.createEmbeddedView(this.tpl);
      }
    });
  }
}

// usage: <button *hasRole="'admin'">Delete</button>`
      },
      {
        caption: 'An attribute directive with host listeners',
        code: `@Directive({
  selector: '[appHighlight]',
  host: {
    '(mouseenter)': 'hovered.set(true)',
    '(mouseleave)': 'hovered.set(false)',
    '[style.background]': 'hovered() ? color() : null'
  }
})
export class HighlightDirective {
  color = input('rgba(255,255,255,0.12)');
  protected readonly hovered = signal(false);
}`
      }
    ]
  },

  '13-custom-pipes': {
    title: 'Custom Pipes',
    whatIsIt:
      'A pipe transforms a value for display inside a template using the | syntax. Angular ships pipes such as date, currency, json and async; a custom pipe is a standalone class with @Pipe and a transform() method.',
    whyUseIt:
      'Formatting logic stays out of components and is reusable in any template. Pure pipes are also cached: they only recompute when their input changes.',
    whenToUseIt:
      'For pure display formatting: truncating text, relative time, file sizes, masking card numbers, translating labels. Avoid pipes that fetch data or mutate state.',
    realWorldScenario:
      'A social feed shows "3 minutes ago" under each post. A timeAgo pipe converts timestamps to friendly text, and a fileSize pipe formats attachment sizes, so both feed and notifications reuse the same formatting.',
    codeExamples: [
      {
        caption: 'A timeAgo pipe',
        code: `import { Pipe, PipeTransform } from '@angular/core';

@Pipe({ name: 'timeAgo' })
export class TimeAgoPipe implements PipeTransform {
  transform(value: string | Date): string {
    const seconds = (Date.now() - new Date(value).getTime()) / 1000;
    if (seconds < 60) return 'just now';
    if (seconds < 3600) return Math.floor(seconds / 60) + ' min ago';
    if (seconds < 86400) return Math.floor(seconds / 3600) + ' h ago';
    return Math.floor(seconds / 86400) + ' d ago';
  }
}`
      },
      {
        caption: 'Using it in a standalone component',
        code: `@Component({
  selector: 'app-feed',
  imports: [TimeAgoPipe, CurrencyPipe],
  template: \`
    @for (post of posts(); track post.id) {
      <p>{{ post.text }} <small>{{ post.createdAt | timeAgo }}</small></p>
    }
  \`
})
export class FeedComponent {}`
      }
    ]
  },

  '14-lifecycle-hooks': {
    title: 'Lifecycle Hooks',
    whatIsIt:
      'Lifecycle hooks are methods Angular calls at defined moments of a component life: ngOnInit after inputs are first set, ngOnChanges on input changes, ngAfterViewInit once the template exists, and ngOnDestroy just before removal.',
    whyUseIt:
      'Some work must happen at a specific time: starting a timer after creation, measuring an element after render, or cleaning up subscriptions so you do not leak memory.',
    whenToUseIt:
      'ngOnInit for initial loading, ngAfterViewInit for DOM measurement or third-party widgets, ngOnDestroy for cleanup. With signals, computed() and effect() often replace ngOnChanges entirely.',
    realWorldScenario:
      'A live trading widget opens a websocket in ngOnInit, initialises a charting library against a canvas in ngAfterViewInit, and closes both in ngOnDestroy so switching tabs does not leave sockets open.',
    codeExamples: [
      {
        caption: 'Init and destroy',
        code: `import { Component, ElementRef, OnDestroy, OnInit, viewChild } from '@angular/core';

@Component({ selector: 'app-price-chart', template: '<canvas #canvas></canvas>' })
export class PriceChartComponent implements OnInit, AfterViewInit, OnDestroy {
  private readonly canvas = viewChild.required<ElementRef<HTMLCanvasElement>>('canvas');
  private socket?: WebSocket;
  private chart?: Chart;

  ngOnInit(): void {
    this.socket = new WebSocket('wss://example.com/prices');
  }

  ngAfterViewInit(): void {
    this.chart = new Chart(this.canvas().nativeElement);
  }

  ngOnDestroy(): void {
    this.socket?.close();
    this.chart?.destroy();
  }
}`
      },
      {
        caption: 'Modern alternative: DestroyRef and effect',
        code: `private readonly destroyRef = inject(DestroyRef);

constructor() {
  const id = setInterval(() => this.tick(), 1000);
  this.destroyRef.onDestroy(() => clearInterval(id));

  // reacts to input changes without ngOnChanges
  effect(() => console.log('symbol changed to', this.symbol()));
}`
      }
    ]
  },

  '15-content-projection': {
    title: 'Content Projection',
    whatIsIt:
      'Content projection lets a component render markup supplied by its caller. You place <ng-content> in the component template, optionally with a select attribute to create named slots.',
    whyUseIt:
      'It turns rigid components into flexible layouts. The component owns structure and styling while the caller owns the content, which avoids dozens of boolean inputs.',
    whenToUseIt:
      'For wrappers and layout shells: cards, panels, modals, tabs, accordions, page headers with action buttons.',
    realWorldScenario:
      'A design system ships CardComponent with header, body and footer slots. The dashboard puts a chart in the body and a refresh button in the footer; the settings page puts a form in the same card. Styling stays consistent everywhere.',
    codeExamples: [
      {
        caption: 'Multi-slot card component',
        code: `@Component({
  selector: 'app-card',
  template: \`
    <section class="card">
      <header><ng-content select="[card-title]" /></header>
      <div class="body"><ng-content /></div>
      <footer><ng-content select="[card-actions]" /></footer>
    </section>
  \`,
  styleUrl: './card.component.scss'
})
export class CardComponent {}`
      },
      {
        caption: 'How a caller fills the slots',
        code: `<app-card>
  <h3 card-title>Monthly revenue</h3>

  <app-revenue-chart [data]="revenue()" />

  <button card-actions (click)="refresh()">Refresh</button>
</app-card>`
      }
    ]
  },

  '16-viewchild': {
    title: 'ViewChild',
    whatIsIt:
      'viewChild() (and viewChildren()) give a component a reference to an element, directive or child component in its own template. The signal-based form returns a signal you read after the view is created; contentChild() does the same for projected content.',
    whyUseIt:
      'Some tasks need the real DOM node or a child API: focusing an input, playing a video, calling reset() on a child form, or measuring size. ViewChild gives typed access without document.querySelector.',
    whenToUseIt:
      'When declarative bindings cannot express what you need. Reach for inputs and outputs first; use viewChild for imperative element or child-component control.',
    realWorldScenario:
      'A chat window auto-scrolls to the newest message. The component holds a viewChild reference to the message list div and sets scrollTop whenever the messages signal changes, and focuses the input after sending.',
    codeExamples: [
      {
        caption: 'Signal-based viewChild',
        code: `import { Component, ElementRef, effect, viewChild } from '@angular/core';

@Component({ selector: 'app-chat', templateUrl: './chat.component.html' })
export class ChatComponent {
  private readonly list = viewChild.required<ElementRef<HTMLDivElement>>('list');
  private readonly input = viewChild.required<ElementRef<HTMLInputElement>>('input');
  readonly messages = signal<Message[]>([]);

  constructor() {
    effect(() => {
      this.messages();                          // depend on messages
      const el = this.list().nativeElement;
      el.scrollTop = el.scrollHeight;           // scroll to bottom
    });
  }

  send(text: string): void {
    this.messages.update((m) => [...m, { id: crypto.randomUUID(), text }]);
    this.input().nativeElement.focus();
  }
}`
      },
      {
        caption: 'Referencing a child component and many children',
        code: `<div #list class="messages">...</div>
<input #input>
<app-message-row *ngFor="let m of messages()" />

// class
private readonly rows = viewChildren(MessageRowComponent);
collapseAll(): void { this.rows().forEach((row) => row.collapse()); }`
      }
    ]
  },

  '17-dynamic-components': {
    title: 'Dynamic Components',
    whatIsIt:
      'Dynamic components are created in code rather than written in a template, using ViewContainerRef.createComponent() or the NgComponentOutlet directive. You get a ComponentRef whose inputs you can set and which you destroy when done.',
    whyUseIt:
      'Sometimes the component to render is only known at runtime: a modal chosen by an action, a widget type from a server config, or a form field driven by metadata. Dynamic creation avoids a giant @switch of every possible component.',
    whenToUseIt:
      'For modal/toast services, plugin architectures, configurable dashboards and metadata-driven forms. Prefer plain templates whenever the set of components is fixed and small.',
    realWorldScenario:
      'An analytics dashboard lets users arrange widgets. The layout is saved as JSON like [{ type: "revenue" }, { type: "signups" }]. A registry maps each type to a lazy-loaded component and NgComponentOutlet renders whatever the user configured.',
    codeExamples: [
      {
        caption: 'A modal service creating components at runtime',
        code: `@Injectable({ providedIn: 'root' })
export class ModalService {
  private readonly appRef = inject(ApplicationRef);
  private readonly injector = inject(EnvironmentInjector);

  open<T>(component: Type<T>, inputs: Record<string, unknown> = {}): ComponentRef<T> {
    const ref = createComponent(component, {
      environmentInjector: this.injector
    });
    Object.entries(inputs).forEach(([key, value]) => ref.setInput(key, value));
    document.body.appendChild(ref.location.nativeElement);
    this.appRef.attachView(ref.hostView);
    return ref;                      // caller calls ref.destroy() to close
  }
}`
      },
      {
        caption: 'Config-driven widgets with NgComponentOutlet',
        code: `@Component({
  selector: 'app-dashboard-grid',
  imports: [NgComponentOutlet],
  template: \`
    @for (widget of widgets(); track widget.id) {
      <ng-container [ngComponentOutlet]="registry[widget.type]"
                    [ngComponentOutletInputs]="{ config: widget }" />
    }
  \`
})
export class DashboardGridComponent {
  readonly registry: Record<string, Type<unknown>> = {
    revenue: RevenueWidgetComponent,
    signups: SignupsWidgetComponent
  };
}`
      }
    ]
  },

  '18-interceptors': {
    title: 'Interceptors',
    whatIsIt:
      'An HTTP interceptor is a function that sits between your code and the network. It receives each request plus a next() handler, so it can clone the request, add headers, log timings, retry, or transform errors. Register them with provideHttpClient(withInterceptors([...])).',
    whyUseIt:
      'Cross-cutting HTTP concerns belong in one place. Without interceptors every service repeats the same token header and error handling, and one forgotten call becomes a bug.',
    whenToUseIt:
      'For authentication headers, correlation ids, global error toasts, loading indicators, caching, retrying idempotent requests, and refreshing expired tokens.',
    realWorldScenario:
      'A SaaS dashboard attaches a JWT to every request. When the API answers 401 the interceptor calls the refresh endpoint once, retries the original request, and on a second failure redirects to /login. Components never see any of it.',
    codeExamples: [
      {
        caption: 'Auth and error interceptors',
        code: `import { HttpErrorResponse, HttpInterceptorFn } from '@angular/common/http';
import { catchError, throwError } from 'rxjs';

export const authInterceptor: HttpInterceptorFn = (req, next) => {
  const token = inject(AuthService).token();
  const authed = token
    ? req.clone({ setHeaders: { Authorization: 'Bearer ' + token } })
    : req;
  return next(authed);
};

export const errorInterceptor: HttpInterceptorFn = (req, next) => {
  const toasts = inject(ToastService);
  return next(req).pipe(
    catchError((error: HttpErrorResponse) => {
      if (error.status === 401) inject(Router).navigate(['/login']);
      else toasts.error(error.error?.message ?? 'Something went wrong');
      return throwError(() => error);
    })
  );
};`
      },
      {
        caption: 'Registering them (order matters)',
        code: `// app.config.ts
provideHttpClient(
  withFetch(),
  withInterceptors([authInterceptor, errorInterceptor])
)`
      }
    ]
  },

  '19-route-guards': {
    title: 'Route Guards',
    whatIsIt:
      'Guards are functions the router calls before activating or leaving a route. canActivate decides whether navigation may proceed, canActivateChild covers children, canDeactivate protects unsaved work, and canMatch chooses between route definitions. They return a boolean, a redirect, or an observable/promise of either.',
    whyUseIt:
      'They keep access rules and "are you sure?" checks in one declarative place instead of scattered checks inside components, and they stop unauthorised screens from even rendering.',
    whenToUseIt:
      'For authentication and role checks, feature flags, onboarding steps that must be completed, and confirming navigation away from a dirty form.',
    realWorldScenario:
      'An HR system exposes /admin/salaries only to managers. authGuard redirects anonymous users to /login with a returnUrl, roleGuard sends non-managers to /forbidden, and canDeactivate warns an admin who edits a salary and tries to leave without saving.',
    codeExamples: [
      {
        caption: 'Functional guards',
        code: `import { CanActivateFn, Router, createUrlTreeFromSnapshot } from '@angular/router';

export const authGuard: CanActivateFn = (route, state) => {
  const auth = inject(AuthService);
  if (auth.isLoggedIn()) return true;
  return inject(Router).createUrlTree(['/login'], {
    queryParams: { returnUrl: state.url }
  });
};

export const roleGuard = (role: string): CanActivateFn => () =>
  inject(AuthService).roles().includes(role) || inject(Router).createUrlTree(['/forbidden']);`
      },
      {
        caption: 'Attaching guards to routes',
        code: `export const routes: Routes = [
  {
    path: 'admin/salaries',
    canActivate: [authGuard, roleGuard('manager')],
    canDeactivate: [(component: SalaryEditComponent) => component.confirmLeave()],
    loadComponent: () => import('./admin/salary-edit.component')
      .then((m) => m.SalaryEditComponent)
  }
];`
      }
    ]
  },

  '20-lazy-loading': {
    title: 'Lazy Loading',
    whatIsIt:
      'Lazy loading defers downloading part of your app until it is needed. Routes use loadComponent or loadChildren with a dynamic import, and templates can use @defer to load a heavy component on interaction, viewport or timer.',
    whyUseIt:
      'A smaller initial bundle means a faster first paint, which matters on mobile networks. Users who never open the admin area never download it.',
    whenToUseIt:
      'For feature areas behind navigation or permissions, and for heavy widgets such as charts, editors and maps that are below the fold.',
    realWorldScenario:
      'A banking app splits routes into dashboard, payments and admin chunks. The dashboard also uses @defer (on viewport) for a chart library, cutting the initial bundle roughly in half and improving Largest Contentful Paint.',
    codeExamples: [
      {
        caption: 'Lazy routes',
        code: `export const routes: Routes = [
  {
    path: 'payments',
    loadChildren: () => import('./payments/payments.routes').then((m) => m.PAYMENT_ROUTES)
  },
  {
    path: 'admin',
    canMatch: [roleGuard('admin')],
    loadComponent: () => import('./admin/admin.component').then((m) => m.AdminComponent)
  }
];`
      },
      {
        caption: 'Deferring a heavy widget in a template',
        code: `@defer (on viewport; prefetch on idle) {
  <app-revenue-chart [data]="revenue()" />
} @placeholder {
  <div class="chart-skeleton"></div>
} @loading (after 100ms; minimum 500ms) {
  <app-spinner />
} @error {
  <p>Chart failed to load</p>
}`
      }
    ]
  },

  '21-state-management': {
    title: 'State Management',
    whatIsIt:
      'State management is how you store and share data that outlives a single component: the logged-in user, a cart, filters, cached lists. In Angular 20 the default answer is a service holding signals; larger apps may add NgRx, NgRx SignalStore or similar.',
    whyUseIt:
      'Passing data through many inputs and outputs becomes fragile as an app grows. A single source of truth keeps views consistent, makes updates predictable and makes debugging much easier.',
    whenToUseIt:
      'Use component signals for local UI state. Promote to a signal-based service when several unrelated components need the same data. Add a full store library only when you need strict patterns, time-travel debugging or complex effects across a large team.',
    realWorldScenario:
      'A project management tool keeps tasks in a signal store with computed selectors for "my tasks" and "overdue". Dragging a card calls store.move(), and the board, sidebar counters and activity feed all update from the same state, with an effect syncing changes to the API.',
    codeExamples: [
      {
        caption: 'A signal store service',
        code: `@Injectable({ providedIn: 'root' })
export class TaskStore {
  private readonly state = signal<{ tasks: Task[]; filter: Filter }>({
    tasks: [],
    filter: 'all'
  });

  readonly tasks    = computed(() => this.state().tasks);
  readonly filter   = computed(() => this.state().filter);
  readonly visible  = computed(() => {
    const { tasks, filter } = this.state();
    return filter === 'all' ? tasks : tasks.filter((t) => t.status === filter);
  });
  readonly overdue  = computed(() => this.tasks().filter((t) => t.due < Date.now()));

  setFilter(filter: Filter): void {
    this.state.update((s) => ({ ...s, filter }));
  }

  move(id: string, status: Status): void {
    this.state.update((s) => ({
      ...s,
      tasks: s.tasks.map((t) => (t.id === id ? { ...t, status } : t))
    }));
  }
}`
      },
      {
        caption: 'Consuming the store',
        code: `export class BoardComponent {
  private readonly store = inject(TaskStore);
  readonly tasks = this.store.visible;

  onDrop(id: string, status: Status): void {
    this.store.move(id, status);
  }
}`
      }
    ]
  },

  '22-performance': {
    title: 'Performance',
    whatIsIt:
      'Performance work in Angular means rendering less and shipping less: signals and OnPush change detection, track expressions in @for, lazy loading and @defer, NgOptimizedImage, and keeping bundles within budgets.',
    whyUseIt:
      'Slow apps lose users and rank worse. Most Angular slowness comes from a few fixable causes: too much change detection, huge lists, oversized bundles and unoptimised images.',
    whenToUseIt:
      'Adopt signals and OnPush from the start. Profile before optimising anything else, using the browser performance panel and the Angular DevTools profiler.',
    realWorldScenario:
      'A logistics dashboard shows 5,000 shipments and feels sluggish. Switching to OnPush plus signals, adding track shipment.id, virtualising the table and deferring the map component brings interaction latency from ~400ms down to under 50ms.',
    codeExamples: [
      {
        caption: 'OnPush plus signals and a stable track',
        code: `@Component({
  selector: 'app-shipment-table',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: \`
    @for (s of shipments(); track s.id) {
      <app-shipment-row [shipment]="s" />
    }
  \`
})
export class ShipmentTableComponent {
  shipments = input.required<Shipment[]>();
}`
      },
      {
        caption: 'Images, budgets and analysis',
        code: `<!-- lazy, sized, priority-aware images -->
<img ngSrc="/assets/hero.jpg" width="1200" height="600" priority>

// angular.json budget guard
"budgets": [
  { "type": "initial", "maximumWarning": "500kB", "maximumError": "1MB" }
]

# inspect what is in the bundle
ng build --stats-json && npx source-map-explorer dist/**/*.js`
      }
    ]
  },

  '23-testing': {
    title: 'Testing',
    whatIsIt:
      'Angular tests run with Jasmine and Karma (or Vitest/Jest) using TestBed to create components in a real DOM. Services can be tested as plain classes, and HTTP calls are verified with provideHttpClientTesting and HttpTestingController.',
    whyUseIt:
      'Tests catch regressions before users do and let you refactor with confidence. They also document how a component is meant to behave.',
    whenToUseIt:
      'Unit-test services and pure logic always. Component-test the behaviour users care about (rendered text, clicks, emitted events) rather than internals. Add end-to-end tests for a few critical flows.',
    realWorldScenario:
      'A checkout total once broke after a discount change. The team added a unit test for the discount service and a component test asserting the rendered total, so the same bug now fails CI instead of reaching production.',
    codeExamples: [
      {
        caption: 'Component test with TestBed',
        code: `import { ComponentFixture, TestBed } from '@angular/core/testing';

describe('ProductCardComponent', () => {
  let fixture: ComponentFixture<ProductCardComponent>;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [ProductCardComponent]
    }).compileComponents();

    fixture = TestBed.createComponent(ProductCardComponent);
    fixture.componentRef.setInput('product', { id: '1', name: 'Mug', price: 9 });
    fixture.detectChanges();
  });

  it('renders the product name', () => {
    const el: HTMLElement = fixture.nativeElement;
    expect(el.querySelector('h3')?.textContent).toContain('Mug');
  });

  it('emits when the button is clicked', () => {
    const spy = jasmine.createSpy();
    fixture.componentInstance.addToCart.subscribe(spy);
    fixture.nativeElement.querySelector('button').click();
    expect(spy).toHaveBeenCalled();
  });
});`
      },
      {
        caption: 'Testing a service that calls HTTP',
        code: `TestBed.configureTestingModule({
  providers: [provideHttpClient(), provideHttpClientTesting()]
});

const service = TestBed.inject(InvoiceService);
const httpMock = TestBed.inject(HttpTestingController);

service.list(1).subscribe((page) => expect(page.items.length).toBe(1));

httpMock.expectOne((r) => r.url === '/api/invoices')
        .flush({ items: [{ id: '1' }] });
httpMock.verify();`
      }
    ]
  },

  '24-deployment': {
    title: 'Deployment',
    whatIsIt:
      'Deployment is building your app for production and serving the result. "ng build" outputs optimised, hashed files into dist/<app>/browser, which any static host or CDN can serve.',
    whyUseIt:
      'The production build enables optimisation, minification, tree shaking and hashed filenames for cache busting, and it is what your users actually download.',
    whenToUseIt:
      'On every release, ideally from CI so builds are reproducible. Use environment configuration for API URLs instead of hard-coding them per environment.',
    realWorldScenario:
      'A marketing site deploys on every merge to main: CI runs lint, tests and ng build, then uploads dist/site/browser to a CDN bucket. Because the app uses client-side routing, the host is configured to rewrite unknown paths to index.html so deep links like /pricing work on refresh.',
    codeExamples: [
      {
        caption: 'Build and preview locally',
        code: `npm run build                       # dist/angular-mastery/browser
npx http-server dist/angular-mastery/browser -p 8080 --proxy http://localhost:8080?

# SPA fallback (nginx)
location / {
  try_files $uri $uri/ /index.html;
}`
      },
      {
        caption: 'A minimal CI pipeline',
        code: `# .github/workflows/deploy.yml
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: npm }
      - run: npm ci
      - run: npm run build -- --configuration production
      - run: npx firebase deploy --only hosting --token "\${{ secrets.FIREBASE_TOKEN }}"`
      }
    ]
  }
};

export const getTopicContent = (slug: string): TopicContent | undefined => TOPIC_CONTENT[slug];
